spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm
    username: springstudent
    password: springstudent
  security:
    user.name: admin
    user.password: $2a$12$zrAuUOa7Eezs7ucJFFyJ9OCPz.i8xG.2ED0oHcNjGxlmDCHpVGgLS
  logging:
    org.springframework: DEBUG
  jpa:
      properties:
        hibernate:
          globally_quoted_identifiers=true:

server.port: 8082
spring.main.banner-mode: off

