spring:
  datasource:
    url: jdbc:mysql://192.168.0.118:3306/CRM
    username: springstudent
    password: springstudent
  security:
    user:
      name: admin
      password: $2a$12$zrAuUOa7Eezs7ucJFFyJ9OCPz.i8xG.2ED0oHcNjGxlmDCHpVGgLS
  logging:
    level:
      org.springframework: DEBUG
  jpa:
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  server:
    port: 8082
  main:
    banner-mode: off